# Generated by Django 5.0 on 2023-12-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procut',
            new_name='Product',
        ),
    ]
