# Generated by Django 5.0 on 2023-12-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('KH', 'Kahve'), ('ÇK', 'Çikolata'), ('AK', 'Aksesuar'), ('FL', 'Fit Lezzetler'), ('FS', 'Fırsatlar')], max_length=2),
        ),
    ]
