# Generated by Django 5.0 on 2023-12-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='kullanici',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='postakodu',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='sehir',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='semt',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='ülke',
        ),
    ]
