# Generated by Django 5.0 on 2023-12-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_locality_customer_ad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sehir',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ad',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cep',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ülke',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='semt',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='kullanici',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='postakodu',
            new_name='zipcode',
        ),
    ]
